// -------------------------------------------------------------
// 
// File Name: C:\Users\bryan\Downloads\viterbi\gm_hdlcoder_commviterbi\Traceback.v
// Created: 2024-06-16 16:50:07
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Traceback
// Source Path: gm_hdlcoder_commviterbi/Viterbi Decoder Subsystem/Viterbi Decoder1/Traceback
// Hierarchy Level: 2
// Model version: 10.10
// 
// Traceback Decoding
// Connects traceback units and adds 8 pipeline registers
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Traceback
          (clk,
           reset,
           enb,
           dec_0,
           dec_1,
           dec_2,
           dec_3,
           idx,
           decoded);


  input   clk;
  input   reset;
  input   enb;
  input   dec_0;  // ufix1
  input   dec_1;  // ufix1
  input   dec_2;  // ufix1
  input   dec_3;  // ufix1
  input   [1:0] idx;  // ufix2
  output  decoded;  // ufix1


  wire dec1_0;  // ufix1
  wire dec1_1;  // ufix1
  wire dec1_2;  // ufix1
  wire dec1_3;  // ufix1
  wire [1:0] idx1;  // ufix2
  wire dec2_0;  // ufix1
  wire dec2_1;  // ufix1
  wire dec2_2;  // ufix1
  wire dec2_3;  // ufix1
  wire [1:0] idx2;  // ufix2
  wire dec3_0;  // ufix1
  wire dec3_1;  // ufix1
  wire dec3_2;  // ufix1
  wire dec3_3;  // ufix1
  wire [1:0] idx3;  // ufix2
  wire dec4_0;  // ufix1
  wire dec4_1;  // ufix1
  wire dec4_2;  // ufix1
  wire dec4_3;  // ufix1
  wire [1:0] idx4;  // ufix2
  wire [3:0] dec4;  // ufix1 [4]
  reg  [3:0] decpipereg1;  // ufix1 [4]
  reg [1:0] idxpipereg1;  // ufix2
  wire dec5_0;  // ufix1
  wire dec5_1;  // ufix1
  wire dec5_2;  // ufix1
  wire dec5_3;  // ufix1
  wire [1:0] idx5;  // ufix2
  wire dec6_0;  // ufix1
  wire dec6_1;  // ufix1
  wire dec6_2;  // ufix1
  wire dec6_3;  // ufix1
  wire [1:0] idx6;  // ufix2
  wire dec7_0;  // ufix1
  wire dec7_1;  // ufix1
  wire dec7_2;  // ufix1
  wire dec7_3;  // ufix1
  wire [1:0] idx7;  // ufix2
  wire dec8_0;  // ufix1
  wire dec8_1;  // ufix1
  wire dec8_2;  // ufix1
  wire dec8_3;  // ufix1
  wire [1:0] idx8;  // ufix2
  wire [3:0] dec8;  // ufix1 [4]
  reg  [3:0] decpipereg2;  // ufix1 [4]
  reg [1:0] idxpipereg2;  // ufix2
  wire dec9_0;  // ufix1
  wire dec9_1;  // ufix1
  wire dec9_2;  // ufix1
  wire dec9_3;  // ufix1
  wire [1:0] idx9;  // ufix2
  wire dec10_0;  // ufix1
  wire dec10_1;  // ufix1
  wire dec10_2;  // ufix1
  wire dec10_3;  // ufix1
  wire [1:0] idx10;  // ufix2
  wire dec11_0;  // ufix1
  wire dec11_1;  // ufix1
  wire dec11_2;  // ufix1
  wire dec11_3;  // ufix1
  wire [1:0] idx11;  // ufix2
  wire dec12_0;  // ufix1
  wire dec12_1;  // ufix1
  wire dec12_2;  // ufix1
  wire dec12_3;  // ufix1
  wire [1:0] idx12;  // ufix2
  wire [3:0] dec12;  // ufix1 [4]
  reg  [3:0] decpipereg3;  // ufix1 [4]
  reg [1:0] idxpipereg3;  // ufix2
  wire dec13_0;  // ufix1
  wire dec13_1;  // ufix1
  wire dec13_2;  // ufix1
  wire dec13_3;  // ufix1
  wire [1:0] idx13;  // ufix2
  wire dec14_0;  // ufix1
  wire dec14_1;  // ufix1
  wire dec14_2;  // ufix1
  wire dec14_3;  // ufix1
  wire [1:0] idx14;  // ufix2
  wire dec15_0;  // ufix1
  wire dec15_1;  // ufix1
  wire dec15_2;  // ufix1
  wire dec15_3;  // ufix1
  wire [1:0] idx15;  // ufix2
  wire dec16_0;  // ufix1
  wire dec16_1;  // ufix1
  wire dec16_2;  // ufix1
  wire dec16_3;  // ufix1
  wire [1:0] idx16;  // ufix2
  wire [3:0] dec16;  // ufix1 [4]
  reg  [3:0] decpipereg4;  // ufix1 [4]
  reg [1:0] idxpipereg4;  // ufix2
  wire dec17_0;  // ufix1
  wire dec17_1;  // ufix1
  wire dec17_2;  // ufix1
  wire dec17_3;  // ufix1
  wire [1:0] idx17;  // ufix2
  wire dec18_0;  // ufix1
  wire dec18_1;  // ufix1
  wire dec18_2;  // ufix1
  wire dec18_3;  // ufix1
  wire [1:0] idx18;  // ufix2
  wire dec19_0;  // ufix1
  wire dec19_1;  // ufix1
  wire dec19_2;  // ufix1
  wire dec19_3;  // ufix1
  wire [1:0] idx19;  // ufix2
  wire dec20_0;  // ufix1
  wire dec20_1;  // ufix1
  wire dec20_2;  // ufix1
  wire dec20_3;  // ufix1
  wire [1:0] idx20;  // ufix2
  wire [3:0] dec20;  // ufix1 [4]
  reg  [3:0] decpipereg5;  // ufix1 [4]
  reg [1:0] idxpipereg5;  // ufix2
  wire dec21_0;  // ufix1
  wire dec21_1;  // ufix1
  wire dec21_2;  // ufix1
  wire dec21_3;  // ufix1
  wire [1:0] idx21;  // ufix2
  wire dec22_0;  // ufix1
  wire dec22_1;  // ufix1
  wire dec22_2;  // ufix1
  wire dec22_3;  // ufix1
  wire [1:0] idx22;  // ufix2
  wire dec23_0;  // ufix1
  wire dec23_1;  // ufix1
  wire dec23_2;  // ufix1
  wire dec23_3;  // ufix1
  wire [1:0] idx23;  // ufix2
  wire dec24_0;  // ufix1
  wire dec24_1;  // ufix1
  wire dec24_2;  // ufix1
  wire dec24_3;  // ufix1
  wire [1:0] idx24;  // ufix2
  wire [3:0] dec24;  // ufix1 [4]
  reg  [3:0] decpipereg6;  // ufix1 [4]
  reg [1:0] idxpipereg6;  // ufix2
  wire dec25_0;  // ufix1
  wire dec25_1;  // ufix1
  wire dec25_2;  // ufix1
  wire dec25_3;  // ufix1
  wire [1:0] idx25;  // ufix2
  wire dec26_0;  // ufix1
  wire dec26_1;  // ufix1
  wire dec26_2;  // ufix1
  wire dec26_3;  // ufix1
  wire [1:0] idx26;  // ufix2
  wire dec27_0;  // ufix1
  wire dec27_1;  // ufix1
  wire dec27_2;  // ufix1
  wire dec27_3;  // ufix1
  wire [1:0] idx27;  // ufix2
  wire dec28_0;  // ufix1
  wire dec28_1;  // ufix1
  wire dec28_2;  // ufix1
  wire dec28_3;  // ufix1
  wire [1:0] idx28;  // ufix2
  wire [3:0] dec28;  // ufix1 [4]
  reg  [3:0] decpipereg7;  // ufix1 [4]
  reg [1:0] idxpipereg7;  // ufix2
  wire dec29_0;  // ufix1
  wire dec29_1;  // ufix1
  wire dec29_2;  // ufix1
  wire dec29_3;  // ufix1
  wire [1:0] idx29;  // ufix2
  wire dec30_0;  // ufix1
  wire dec30_1;  // ufix1
  wire dec30_2;  // ufix1
  wire dec30_3;  // ufix1
  wire [1:0] idx30;  // ufix2
  wire dec31_0;  // ufix1
  wire dec31_1;  // ufix1
  wire dec31_2;  // ufix1
  wire dec31_3;  // ufix1
  wire [1:0] idx31;  // ufix2
  wire dec32deadOut_0;  // ufix1
  wire dec32deadOut_1;  // ufix1
  wire dec32deadOut_2;  // ufix1
  wire dec32deadOut_3;  // ufix1
  wire [1:0] idx32;  // ufix2
  reg [1:0] idxpipereg8;  // ufix2


  // Traceback Component1
  TracebackUnit u_TracebackComp_inst1 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec_0),  // ufix1
                                       .dec_in_1(dec_1),  // ufix1
                                       .dec_in_2(dec_2),  // ufix1
                                       .dec_in_3(dec_3),  // ufix1
                                       .idx_in(idx),  // ufix2
                                       .dec_out_0(dec1_0),  // ufix1
                                       .dec_out_1(dec1_1),  // ufix1
                                       .dec_out_2(dec1_2),  // ufix1
                                       .dec_out_3(dec1_3),  // ufix1
                                       .idx_out(idx1)  // ufix2
                                       );

  // Traceback Component2
  TracebackUnit u_TracebackComp_inst2 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec1_0),  // ufix1
                                       .dec_in_1(dec1_1),  // ufix1
                                       .dec_in_2(dec1_2),  // ufix1
                                       .dec_in_3(dec1_3),  // ufix1
                                       .idx_in(idx1),  // ufix2
                                       .dec_out_0(dec2_0),  // ufix1
                                       .dec_out_1(dec2_1),  // ufix1
                                       .dec_out_2(dec2_2),  // ufix1
                                       .dec_out_3(dec2_3),  // ufix1
                                       .idx_out(idx2)  // ufix2
                                       );

  // Traceback Component3
  TracebackUnit u_TracebackComp_inst3 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec2_0),  // ufix1
                                       .dec_in_1(dec2_1),  // ufix1
                                       .dec_in_2(dec2_2),  // ufix1
                                       .dec_in_3(dec2_3),  // ufix1
                                       .idx_in(idx2),  // ufix2
                                       .dec_out_0(dec3_0),  // ufix1
                                       .dec_out_1(dec3_1),  // ufix1
                                       .dec_out_2(dec3_2),  // ufix1
                                       .dec_out_3(dec3_3),  // ufix1
                                       .idx_out(idx3)  // ufix2
                                       );

  // Traceback Component4
  TracebackUnit u_TracebackComp_inst4 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec3_0),  // ufix1
                                       .dec_in_1(dec3_1),  // ufix1
                                       .dec_in_2(dec3_2),  // ufix1
                                       .dec_in_3(dec3_3),  // ufix1
                                       .idx_in(idx3),  // ufix2
                                       .dec_out_0(dec4_0),  // ufix1
                                       .dec_out_1(dec4_1),  // ufix1
                                       .dec_out_2(dec4_2),  // ufix1
                                       .dec_out_3(dec4_3),  // ufix1
                                       .idx_out(idx4)  // ufix2
                                       );

  assign dec4[0] = dec4_0;
  assign dec4[1] = dec4_1;
  assign dec4[2] = dec4_2;
  assign dec4[3] = dec4_3;

  // Decision pipeline register1
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_process
      if (reset == 1'b1) begin
        decpipereg1 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg1 <= dec4;
        end
      end
    end



  // Index pipeline register1
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_process
      if (reset == 1'b1) begin
        idxpipereg1 <= 2'b00;
      end
      else begin
        if (enb) begin
          idxpipereg1 <= idx4;
        end
      end
    end



  // Traceback Component5
  TracebackUnit u_TracebackComp_inst5 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(decpipereg1[0]),  // ufix1
                                       .dec_in_1(decpipereg1[1]),  // ufix1
                                       .dec_in_2(decpipereg1[2]),  // ufix1
                                       .dec_in_3(decpipereg1[3]),  // ufix1
                                       .idx_in(idxpipereg1),  // ufix2
                                       .dec_out_0(dec5_0),  // ufix1
                                       .dec_out_1(dec5_1),  // ufix1
                                       .dec_out_2(dec5_2),  // ufix1
                                       .dec_out_3(dec5_3),  // ufix1
                                       .idx_out(idx5)  // ufix2
                                       );

  // Traceback Component6
  TracebackUnit u_TracebackComp_inst6 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec5_0),  // ufix1
                                       .dec_in_1(dec5_1),  // ufix1
                                       .dec_in_2(dec5_2),  // ufix1
                                       .dec_in_3(dec5_3),  // ufix1
                                       .idx_in(idx5),  // ufix2
                                       .dec_out_0(dec6_0),  // ufix1
                                       .dec_out_1(dec6_1),  // ufix1
                                       .dec_out_2(dec6_2),  // ufix1
                                       .dec_out_3(dec6_3),  // ufix1
                                       .idx_out(idx6)  // ufix2
                                       );

  // Traceback Component7
  TracebackUnit u_TracebackComp_inst7 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec6_0),  // ufix1
                                       .dec_in_1(dec6_1),  // ufix1
                                       .dec_in_2(dec6_2),  // ufix1
                                       .dec_in_3(dec6_3),  // ufix1
                                       .idx_in(idx6),  // ufix2
                                       .dec_out_0(dec7_0),  // ufix1
                                       .dec_out_1(dec7_1),  // ufix1
                                       .dec_out_2(dec7_2),  // ufix1
                                       .dec_out_3(dec7_3),  // ufix1
                                       .idx_out(idx7)  // ufix2
                                       );

  // Traceback Component8
  TracebackUnit u_TracebackComp_inst8 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec7_0),  // ufix1
                                       .dec_in_1(dec7_1),  // ufix1
                                       .dec_in_2(dec7_2),  // ufix1
                                       .dec_in_3(dec7_3),  // ufix1
                                       .idx_in(idx7),  // ufix2
                                       .dec_out_0(dec8_0),  // ufix1
                                       .dec_out_1(dec8_1),  // ufix1
                                       .dec_out_2(dec8_2),  // ufix1
                                       .dec_out_3(dec8_3),  // ufix1
                                       .idx_out(idx8)  // ufix2
                                       );

  assign dec8[0] = dec8_0;
  assign dec8[1] = dec8_1;
  assign dec8[2] = dec8_2;
  assign dec8[3] = dec8_3;

  // Decision pipeline register2
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_1_process
      if (reset == 1'b1) begin
        decpipereg2 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg2 <= dec8;
        end
      end
    end



  // Index pipeline register2
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_1_process
      if (reset == 1'b1) begin
        idxpipereg2 <= 2'b00;
      end
      else begin
        if (enb) begin
          idxpipereg2 <= idx8;
        end
      end
    end



  // Traceback Component9
  TracebackUnit u_TracebackComp_inst9 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(decpipereg2[0]),  // ufix1
                                       .dec_in_1(decpipereg2[1]),  // ufix1
                                       .dec_in_2(decpipereg2[2]),  // ufix1
                                       .dec_in_3(decpipereg2[3]),  // ufix1
                                       .idx_in(idxpipereg2),  // ufix2
                                       .dec_out_0(dec9_0),  // ufix1
                                       .dec_out_1(dec9_1),  // ufix1
                                       .dec_out_2(dec9_2),  // ufix1
                                       .dec_out_3(dec9_3),  // ufix1
                                       .idx_out(idx9)  // ufix2
                                       );

  // Traceback Component10
  TracebackUnit u_TracebackComp_inst10 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec9_0),  // ufix1
                                        .dec_in_1(dec9_1),  // ufix1
                                        .dec_in_2(dec9_2),  // ufix1
                                        .dec_in_3(dec9_3),  // ufix1
                                        .idx_in(idx9),  // ufix2
                                        .dec_out_0(dec10_0),  // ufix1
                                        .dec_out_1(dec10_1),  // ufix1
                                        .dec_out_2(dec10_2),  // ufix1
                                        .dec_out_3(dec10_3),  // ufix1
                                        .idx_out(idx10)  // ufix2
                                        );

  // Traceback Component11
  TracebackUnit u_TracebackComp_inst11 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec10_0),  // ufix1
                                        .dec_in_1(dec10_1),  // ufix1
                                        .dec_in_2(dec10_2),  // ufix1
                                        .dec_in_3(dec10_3),  // ufix1
                                        .idx_in(idx10),  // ufix2
                                        .dec_out_0(dec11_0),  // ufix1
                                        .dec_out_1(dec11_1),  // ufix1
                                        .dec_out_2(dec11_2),  // ufix1
                                        .dec_out_3(dec11_3),  // ufix1
                                        .idx_out(idx11)  // ufix2
                                        );

  // Traceback Component12
  TracebackUnit u_TracebackComp_inst12 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec11_0),  // ufix1
                                        .dec_in_1(dec11_1),  // ufix1
                                        .dec_in_2(dec11_2),  // ufix1
                                        .dec_in_3(dec11_3),  // ufix1
                                        .idx_in(idx11),  // ufix2
                                        .dec_out_0(dec12_0),  // ufix1
                                        .dec_out_1(dec12_1),  // ufix1
                                        .dec_out_2(dec12_2),  // ufix1
                                        .dec_out_3(dec12_3),  // ufix1
                                        .idx_out(idx12)  // ufix2
                                        );

  assign dec12[0] = dec12_0;
  assign dec12[1] = dec12_1;
  assign dec12[2] = dec12_2;
  assign dec12[3] = dec12_3;

  // Decision pipeline register3
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_2_process
      if (reset == 1'b1) begin
        decpipereg3 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg3 <= dec12;
        end
      end
    end



  // Index pipeline register3
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_2_process
      if (reset == 1'b1) begin
        idxpipereg3 <= 2'b00;
      end
      else begin
        if (enb) begin
          idxpipereg3 <= idx12;
        end
      end
    end



  // Traceback Component13
  TracebackUnit u_TracebackComp_inst13 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(decpipereg3[0]),  // ufix1
                                        .dec_in_1(decpipereg3[1]),  // ufix1
                                        .dec_in_2(decpipereg3[2]),  // ufix1
                                        .dec_in_3(decpipereg3[3]),  // ufix1
                                        .idx_in(idxpipereg3),  // ufix2
                                        .dec_out_0(dec13_0),  // ufix1
                                        .dec_out_1(dec13_1),  // ufix1
                                        .dec_out_2(dec13_2),  // ufix1
                                        .dec_out_3(dec13_3),  // ufix1
                                        .idx_out(idx13)  // ufix2
                                        );

  // Traceback Component14
  TracebackUnit u_TracebackComp_inst14 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec13_0),  // ufix1
                                        .dec_in_1(dec13_1),  // ufix1
                                        .dec_in_2(dec13_2),  // ufix1
                                        .dec_in_3(dec13_3),  // ufix1
                                        .idx_in(idx13),  // ufix2
                                        .dec_out_0(dec14_0),  // ufix1
                                        .dec_out_1(dec14_1),  // ufix1
                                        .dec_out_2(dec14_2),  // ufix1
                                        .dec_out_3(dec14_3),  // ufix1
                                        .idx_out(idx14)  // ufix2
                                        );

  // Traceback Component15
  TracebackUnit u_TracebackComp_inst15 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec14_0),  // ufix1
                                        .dec_in_1(dec14_1),  // ufix1
                                        .dec_in_2(dec14_2),  // ufix1
                                        .dec_in_3(dec14_3),  // ufix1
                                        .idx_in(idx14),  // ufix2
                                        .dec_out_0(dec15_0),  // ufix1
                                        .dec_out_1(dec15_1),  // ufix1
                                        .dec_out_2(dec15_2),  // ufix1
                                        .dec_out_3(dec15_3),  // ufix1
                                        .idx_out(idx15)  // ufix2
                                        );

  // Traceback Component16
  TracebackUnit u_TracebackComp_inst16 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec15_0),  // ufix1
                                        .dec_in_1(dec15_1),  // ufix1
                                        .dec_in_2(dec15_2),  // ufix1
                                        .dec_in_3(dec15_3),  // ufix1
                                        .idx_in(idx15),  // ufix2
                                        .dec_out_0(dec16_0),  // ufix1
                                        .dec_out_1(dec16_1),  // ufix1
                                        .dec_out_2(dec16_2),  // ufix1
                                        .dec_out_3(dec16_3),  // ufix1
                                        .idx_out(idx16)  // ufix2
                                        );

  assign dec16[0] = dec16_0;
  assign dec16[1] = dec16_1;
  assign dec16[2] = dec16_2;
  assign dec16[3] = dec16_3;

  // Decision pipeline register4
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_3_process
      if (reset == 1'b1) begin
        decpipereg4 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg4 <= dec16;
        end
      end
    end



  // Index pipeline register4
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_3_process
      if (reset == 1'b1) begin
        idxpipereg4 <= 2'b00;
      end
      else begin
        if (enb) begin
          idxpipereg4 <= idx16;
        end
      end
    end



  // Traceback Component17
  TracebackUnit u_TracebackComp_inst17 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(decpipereg4[0]),  // ufix1
                                        .dec_in_1(decpipereg4[1]),  // ufix1
                                        .dec_in_2(decpipereg4[2]),  // ufix1
                                        .dec_in_3(decpipereg4[3]),  // ufix1
                                        .idx_in(idxpipereg4),  // ufix2
                                        .dec_out_0(dec17_0),  // ufix1
                                        .dec_out_1(dec17_1),  // ufix1
                                        .dec_out_2(dec17_2),  // ufix1
                                        .dec_out_3(dec17_3),  // ufix1
                                        .idx_out(idx17)  // ufix2
                                        );

  // Traceback Component18
  TracebackUnit u_TracebackComp_inst18 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec17_0),  // ufix1
                                        .dec_in_1(dec17_1),  // ufix1
                                        .dec_in_2(dec17_2),  // ufix1
                                        .dec_in_3(dec17_3),  // ufix1
                                        .idx_in(idx17),  // ufix2
                                        .dec_out_0(dec18_0),  // ufix1
                                        .dec_out_1(dec18_1),  // ufix1
                                        .dec_out_2(dec18_2),  // ufix1
                                        .dec_out_3(dec18_3),  // ufix1
                                        .idx_out(idx18)  // ufix2
                                        );

  // Traceback Component19
  TracebackUnit u_TracebackComp_inst19 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec18_0),  // ufix1
                                        .dec_in_1(dec18_1),  // ufix1
                                        .dec_in_2(dec18_2),  // ufix1
                                        .dec_in_3(dec18_3),  // ufix1
                                        .idx_in(idx18),  // ufix2
                                        .dec_out_0(dec19_0),  // ufix1
                                        .dec_out_1(dec19_1),  // ufix1
                                        .dec_out_2(dec19_2),  // ufix1
                                        .dec_out_3(dec19_3),  // ufix1
                                        .idx_out(idx19)  // ufix2
                                        );

  // Traceback Component20
  TracebackUnit u_TracebackComp_inst20 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec19_0),  // ufix1
                                        .dec_in_1(dec19_1),  // ufix1
                                        .dec_in_2(dec19_2),  // ufix1
                                        .dec_in_3(dec19_3),  // ufix1
                                        .idx_in(idx19),  // ufix2
                                        .dec_out_0(dec20_0),  // ufix1
                                        .dec_out_1(dec20_1),  // ufix1
                                        .dec_out_2(dec20_2),  // ufix1
                                        .dec_out_3(dec20_3),  // ufix1
                                        .idx_out(idx20)  // ufix2
                                        );

  assign dec20[0] = dec20_0;
  assign dec20[1] = dec20_1;
  assign dec20[2] = dec20_2;
  assign dec20[3] = dec20_3;

  // Decision pipeline register5
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_4_process
      if (reset == 1'b1) begin
        decpipereg5 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg5 <= dec20;
        end
      end
    end



  // Index pipeline register5
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_4_process
      if (reset == 1'b1) begin
        idxpipereg5 <= 2'b00;
      end
      else begin
        if (enb) begin
          idxpipereg5 <= idx20;
        end
      end
    end



  // Traceback Component21
  TracebackUnit u_TracebackComp_inst21 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(decpipereg5[0]),  // ufix1
                                        .dec_in_1(decpipereg5[1]),  // ufix1
                                        .dec_in_2(decpipereg5[2]),  // ufix1
                                        .dec_in_3(decpipereg5[3]),  // ufix1
                                        .idx_in(idxpipereg5),  // ufix2
                                        .dec_out_0(dec21_0),  // ufix1
                                        .dec_out_1(dec21_1),  // ufix1
                                        .dec_out_2(dec21_2),  // ufix1
                                        .dec_out_3(dec21_3),  // ufix1
                                        .idx_out(idx21)  // ufix2
                                        );

  // Traceback Component22
  TracebackUnit u_TracebackComp_inst22 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec21_0),  // ufix1
                                        .dec_in_1(dec21_1),  // ufix1
                                        .dec_in_2(dec21_2),  // ufix1
                                        .dec_in_3(dec21_3),  // ufix1
                                        .idx_in(idx21),  // ufix2
                                        .dec_out_0(dec22_0),  // ufix1
                                        .dec_out_1(dec22_1),  // ufix1
                                        .dec_out_2(dec22_2),  // ufix1
                                        .dec_out_3(dec22_3),  // ufix1
                                        .idx_out(idx22)  // ufix2
                                        );

  // Traceback Component23
  TracebackUnit u_TracebackComp_inst23 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec22_0),  // ufix1
                                        .dec_in_1(dec22_1),  // ufix1
                                        .dec_in_2(dec22_2),  // ufix1
                                        .dec_in_3(dec22_3),  // ufix1
                                        .idx_in(idx22),  // ufix2
                                        .dec_out_0(dec23_0),  // ufix1
                                        .dec_out_1(dec23_1),  // ufix1
                                        .dec_out_2(dec23_2),  // ufix1
                                        .dec_out_3(dec23_3),  // ufix1
                                        .idx_out(idx23)  // ufix2
                                        );

  // Traceback Component24
  TracebackUnit u_TracebackComp_inst24 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec23_0),  // ufix1
                                        .dec_in_1(dec23_1),  // ufix1
                                        .dec_in_2(dec23_2),  // ufix1
                                        .dec_in_3(dec23_3),  // ufix1
                                        .idx_in(idx23),  // ufix2
                                        .dec_out_0(dec24_0),  // ufix1
                                        .dec_out_1(dec24_1),  // ufix1
                                        .dec_out_2(dec24_2),  // ufix1
                                        .dec_out_3(dec24_3),  // ufix1
                                        .idx_out(idx24)  // ufix2
                                        );

  assign dec24[0] = dec24_0;
  assign dec24[1] = dec24_1;
  assign dec24[2] = dec24_2;
  assign dec24[3] = dec24_3;

  // Decision pipeline register6
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_5_process
      if (reset == 1'b1) begin
        decpipereg6 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg6 <= dec24;
        end
      end
    end



  // Index pipeline register6
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_5_process
      if (reset == 1'b1) begin
        idxpipereg6 <= 2'b00;
      end
      else begin
        if (enb) begin
          idxpipereg6 <= idx24;
        end
      end
    end



  // Traceback Component25
  TracebackUnit u_TracebackComp_inst25 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(decpipereg6[0]),  // ufix1
                                        .dec_in_1(decpipereg6[1]),  // ufix1
                                        .dec_in_2(decpipereg6[2]),  // ufix1
                                        .dec_in_3(decpipereg6[3]),  // ufix1
                                        .idx_in(idxpipereg6),  // ufix2
                                        .dec_out_0(dec25_0),  // ufix1
                                        .dec_out_1(dec25_1),  // ufix1
                                        .dec_out_2(dec25_2),  // ufix1
                                        .dec_out_3(dec25_3),  // ufix1
                                        .idx_out(idx25)  // ufix2
                                        );

  // Traceback Component26
  TracebackUnit u_TracebackComp_inst26 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec25_0),  // ufix1
                                        .dec_in_1(dec25_1),  // ufix1
                                        .dec_in_2(dec25_2),  // ufix1
                                        .dec_in_3(dec25_3),  // ufix1
                                        .idx_in(idx25),  // ufix2
                                        .dec_out_0(dec26_0),  // ufix1
                                        .dec_out_1(dec26_1),  // ufix1
                                        .dec_out_2(dec26_2),  // ufix1
                                        .dec_out_3(dec26_3),  // ufix1
                                        .idx_out(idx26)  // ufix2
                                        );

  // Traceback Component27
  TracebackUnit u_TracebackComp_inst27 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec26_0),  // ufix1
                                        .dec_in_1(dec26_1),  // ufix1
                                        .dec_in_2(dec26_2),  // ufix1
                                        .dec_in_3(dec26_3),  // ufix1
                                        .idx_in(idx26),  // ufix2
                                        .dec_out_0(dec27_0),  // ufix1
                                        .dec_out_1(dec27_1),  // ufix1
                                        .dec_out_2(dec27_2),  // ufix1
                                        .dec_out_3(dec27_3),  // ufix1
                                        .idx_out(idx27)  // ufix2
                                        );

  // Traceback Component28
  TracebackUnit u_TracebackComp_inst28 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec27_0),  // ufix1
                                        .dec_in_1(dec27_1),  // ufix1
                                        .dec_in_2(dec27_2),  // ufix1
                                        .dec_in_3(dec27_3),  // ufix1
                                        .idx_in(idx27),  // ufix2
                                        .dec_out_0(dec28_0),  // ufix1
                                        .dec_out_1(dec28_1),  // ufix1
                                        .dec_out_2(dec28_2),  // ufix1
                                        .dec_out_3(dec28_3),  // ufix1
                                        .idx_out(idx28)  // ufix2
                                        );

  assign dec28[0] = dec28_0;
  assign dec28[1] = dec28_1;
  assign dec28[2] = dec28_2;
  assign dec28[3] = dec28_3;

  // Decision pipeline register7
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_6_process
      if (reset == 1'b1) begin
        decpipereg7 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg7 <= dec28;
        end
      end
    end



  // Index pipeline register7
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_6_process
      if (reset == 1'b1) begin
        idxpipereg7 <= 2'b00;
      end
      else begin
        if (enb) begin
          idxpipereg7 <= idx28;
        end
      end
    end



  // Traceback Component29
  TracebackUnit u_TracebackComp_inst29 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(decpipereg7[0]),  // ufix1
                                        .dec_in_1(decpipereg7[1]),  // ufix1
                                        .dec_in_2(decpipereg7[2]),  // ufix1
                                        .dec_in_3(decpipereg7[3]),  // ufix1
                                        .idx_in(idxpipereg7),  // ufix2
                                        .dec_out_0(dec29_0),  // ufix1
                                        .dec_out_1(dec29_1),  // ufix1
                                        .dec_out_2(dec29_2),  // ufix1
                                        .dec_out_3(dec29_3),  // ufix1
                                        .idx_out(idx29)  // ufix2
                                        );

  // Traceback Component30
  TracebackUnit u_TracebackComp_inst30 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec29_0),  // ufix1
                                        .dec_in_1(dec29_1),  // ufix1
                                        .dec_in_2(dec29_2),  // ufix1
                                        .dec_in_3(dec29_3),  // ufix1
                                        .idx_in(idx29),  // ufix2
                                        .dec_out_0(dec30_0),  // ufix1
                                        .dec_out_1(dec30_1),  // ufix1
                                        .dec_out_2(dec30_2),  // ufix1
                                        .dec_out_3(dec30_3),  // ufix1
                                        .idx_out(idx30)  // ufix2
                                        );

  // Traceback Component31
  TracebackUnit u_TracebackComp_inst31 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec30_0),  // ufix1
                                        .dec_in_1(dec30_1),  // ufix1
                                        .dec_in_2(dec30_2),  // ufix1
                                        .dec_in_3(dec30_3),  // ufix1
                                        .idx_in(idx30),  // ufix2
                                        .dec_out_0(dec31_0),  // ufix1
                                        .dec_out_1(dec31_1),  // ufix1
                                        .dec_out_2(dec31_2),  // ufix1
                                        .dec_out_3(dec31_3),  // ufix1
                                        .idx_out(idx31)  // ufix2
                                        );

  // Traceback Component32
  // Decision pipeline register8
  TracebackUnit u_TracebackComp_inst32 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec31_0),  // ufix1
                                        .dec_in_1(dec31_1),  // ufix1
                                        .dec_in_2(dec31_2),  // ufix1
                                        .dec_in_3(dec31_3),  // ufix1
                                        .idx_in(idx31),  // ufix2
                                        .dec_out_0(dec32deadOut_0),  // ufix1
                                        .dec_out_1(dec32deadOut_1),  // ufix1
                                        .dec_out_2(dec32deadOut_2),  // ufix1
                                        .dec_out_3(dec32deadOut_3),  // ufix1
                                        .idx_out(idx32)  // ufix2
                                        );

  // Index pipeline register8
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_7_process
      if (reset == 1'b1) begin
        idxpipereg8 <= 2'b00;
      end
      else begin
        if (enb) begin
          idxpipereg8 <= idx32;
        end
      end
    end



  assign decoded = idxpipereg8[1];



endmodule  // Traceback

